server/api/payment.js
server/api/users.js
server/util/gcloudPub.js

+ Add verify uuid field in verify log
! Fix review

+ Add like amount string field in tx log

---

components/LikeRegisterForm.vue
pages/edit.vue
store/modules/actions/user.js
util/EthHelper.js

+ Add web3 account polling check

---

components/LikeRegisterForm.vue
constant/index.js
package-lock.json
package.json
pages/register.vue

eg : http://likecoin.store/register?redirect=https%3A%2F%2Foice.com%2F%3Fa%3Db%26b%3Dc

+ Add support to redirect in `/register`

---

assets/theme.scss
layouts/defaultWithHeader.vue
locales/en.json
locales/zh.json
pages/whitepaper.vue

Update whitepaper page

---

components/NumberInput.vue
components/dialogs/TxDialog.vue
components/toolbars/ToolBars.vue
components/toolbars/TxToolbar.vue
layouts/base.vue
layouts/narrowWithHeader.vue
locales/en.json
locales/zh.json
pages/_id/index.vue
pages/in/tokensale/index.vue
server/api/payment.js
store/modules/actions/ui.js

! Fix route `tx-id` not working
+ Add customizable number input error
+ Fine tune disableError logic

! Fix misc issue on presale UI

---

package-lock.json
package.json
server/api/kyc.js
server/api/users.js
server/util/web3.js
test/express.test.js
util/EthHelper.js
util/User.js

= Sign plaintext instead of typedSignature for `user` and `kyc`

---

assets/index.scss
nuxt.config.js

Fix mystery font issue on Safari

---

server/util/web3.js

https://firebase.google.com/docs/firestore/manage-data/transactions
但係 doc 係覺得我唔需要 await 個 update 的

+ Use async await in web3 firestore tx

---

components/KYCForm.vue
pages/in/edit.vue
pages/in/tokensale/index.vue

Renable/fix countdown/tokensale related display logic

! Fix presale <-> tokensale UI logic

---

components/TransactionHistory.vue
util/EthHelper.js

+ Support display of transferAndLock in tx page

! Fix txHistory display error

---

components/toolbars/ToolBars.vue

Fixes https://github.com/likecoin/likecoin-store/issues/212

- Block opera for now until better solution

---

pages/in/edit.vue

! Dim verified email address field when editing

---

nuxt.config.js
package-lock.json
package.json

https://github.com/likecoin/likecoin-store/pull/252 + classList
not sure if classList should be in global header, so separate PR

!Polyfill classlist

---

components/LanguageSwitch.vue
locales/client/cn.json
locales/client/de.json
locales/client/en.json
locales/client/es.json
locales/client/fr.json
locales/client/it.json
locales/client/ja.json
locales/client/ko.json
locales/client/pt.json
locales/client/ru.json
locales/client/zh.json
locales/index.js
locales/server/cn.json
locales/server/de.json
locales/server/en.json
locales/server/es.json
locales/server/fr.json
locales/server/it.json
locales/server/ja.json
locales/server/ko.json
locales/server/pt.json
locales/server/ru.json
locales/server/zh.json
plugins/vue-i18n.js
server/index.js

also split client and server(email) locale

+ Make locale loading async

---

constant/index.js
util/EthHelper.js

To sync with tx-poll, in fact +1 confirm(6) compared to tx-poll for UX

+ Check number of block confirm in EthHelper

---

components/Mission/Item.vue
server/api/payment.js
util/ValidationHelper.js

not sure how to fix the mess that is `seen`, `done`, `isClaimed`, and `status === 'pending'`

+ Add mission pending status

---

pages/_id/index.vue

+ Add address mask in payment page

---

store/modules/getters/mission.js

Best effort mission sorting

---

components/dialogs/MissionDialog.vue
locales/client/en.json

= Move step mission to beginning of function

---

components/Mission/Item.vue
store/modules/getters/mission.js

since not better elegant way can be thought of

+ Add JoinTokenSale reward display hack

---

pages/in/index.vue

seems this part should only exist in `UserInfoForm`

! Fix undefined dialog error

---

components/KYCForm.vue
components/LikeRegisterForm.vue
components/UserInfoForm.vue
pages/in/index.vue

This reverts commit 846e87a846e3b377b708c76d7bbc6ada233f5281.

Revert "- Remove unused `InputDialog` and `showEmail` in UserInfoForm"

---

components/toolbars/ToolBars.vue
util/User.js

! Fix user with verified email cannot sign userinfo

+ Add snackbar

---

assets/_variables.scss
assets/index.scss
components/dialogs/BaseDialog.vue
components/dialogs/MissionDialog.vue
components/dialogs/TrustDialog.vue
pages/in/bonus/index.vue
pages/ref/_id/index.vue

Fix layout

---

components/toolbars/ToolBars.vue
util/api/api.js

! Fix snackbar warnings

---

server/api/kyc.js

This reverts commit d3546f687ad674dd65cd0f62875e0ccf432f5e99.

Revert "+ Add `startKYC` auto payout event"

---

components/KYCForm.vue

! Fix blocking when cancel file browsing

---

components/KYCForm.vue

prevent time gap between upload is picked and `documentFile0`/`documentFile1` populated

+ Add button `:disabled` UX hint for adv KYC upload

---

assets/_mixin.scss
assets/index.scss
components/Mission/ItemPlaceholder.vue
components/dialogs/BaseDialog.vue
components/dialogs/BlockerDialog.vue
components/dialogs/TxDialog.vue
locales/client/en.json

Fix collapsed dialog in iOS 10

Rebuild some dialogs using BaseDialog

---

package-lock.json
package.json
test/e2e/specs/mission.js
test/e2e/specs/user.js
test/e2e/util/index.js
test/runner.js
test/stub/server/config/accounts.js
test/stub/server/util/firebase.js

+ Add delegator account for unit test

+ Add send like and eth unit test

---

locales/client/cn.json
locales/client/de.json
locales/client/en.json
locales/client/es.json
locales/client/fr.json
locales/client/it.json
locales/client/ja.json
locales/client/ko.json
locales/client/pt.json
locales/client/zh.json
nuxt.config.js
server/api/kyc.js
server/api/users.js

https://developers.google.com/recaptcha/docs/faq

! Make reCAPTCHA accessible globally

---

pages/in/settings.vue

For old user and user cancelling signing

! Fix settings page

---

locales/client/en.json
locales/client/zh.json
nuxt.config.js
pages/in/embed/_id/button.vue
pages/in/embed/_id/index.vue
server/api/oembed.js
test/api/oembed.test.js

support subdomain, amount and referrer passing

+ Update oembed to support more feature

---

components/BlockProgress.vue
pages/in/embed/_id/index.vue

need to default loading indicator to not show up, probably is against what it does initially

! Fix embed superlike not working when js disabled

---

pages/in/embed/_id/index.vue

未做新 UI but fix trivial problem spotted first

! Fix embed superlike styling issue

---

pages/in/embed/_id/index.vue
server/api/oembed.js

! Fix default height setting in oembed iframe

+ Add responsive version for embeded superlike

---

pages/in/embed/_id/index.vue
server/api/oembed.js

Reverts likecoin/likecoin-store#602

Revert "+ Add responsive version for embeded superlike"

---

.babelrc
backpack.config.js
package.json
server/api/users.js
server/util/firebase.js
server/util/gcloudPub.js
server/util/jwt.js
server/util/poller.js
server/util/stripe.js
server/util/web3.js
test/api/iap.test.js
test/api/mission.test.js
test/api/oembed.test.js
test/api/payment.test.js
test/api/user.test.js
test/stub/server/util/firebase.js
webpack.config.js

please wait until ci actually pass

- Clean up babel and webpack config

---

pages/in/embed/_id/button.vue

scenario: 2 click then 3 click
before: event:2, event:5
after: event:2, event:3

! Fix likebutton should send batch count instead of sum

---

pages/in/embed/_id/button.vue
util/api/api.js

+Add user state and stats for likebutton

---

server/api/oembed.js

need to update master since all oembed api request, including rinkeby, goes through master

+ Reply likebutton oembed with button subdomain

---

components/home/MansoryArticleList.vue
package-lock.json
store/modules/getters/staticData.js
store/modules/staticData.js

! Fix suggested list ordering not preserved

---

server/api/mission.js
server/api/payment.js
server/api/social/facebook.js
server/api/social/flickr.js
server/api/social/index.js
server/api/social/instagram.js
server/api/social/link.js
server/api/social/medium.js
server/api/social/twitter.js
server/api/users.js
server/config/config.js
server/util/jwt.js
test/api/axiosist.js
test/api/jwt.js
test/api/mission.test.js
test/api/payment.test.js
test/api/social.test.js
test/api/user.test.js
test/e2e/specs/tx.js
test/e2e/specs/user.js
test/e2e/util/index.js
test/stub/server/util/firebase.js

Done:
+ Add AUD ISS and permissions field
+ Add RSA support
+ Add jwtId for session control
TODO in future:
+ Add void of session

[WIP] JWT revamp

---

util/EthHelper.js

! Fix missing prompt for metamask permission in wallet login

---

server/api/payment.js
server/api/users.js
test/api/user.test.js
util/api/api.js

- Remove unused get user detail by addr api

! Fix cannot fetch tx history with oauth login

---

server/util/api/social.js
server/util/api/users.js

! Fix auto social/oauth linking

! Block user removing all visible oauth login platform

---

locales/client/zh.json

https://github.com/likecoin/likecoin-store/pull/882

* Update locale

---

components/PlatformIconBar.vue

https://developers.google.com/search/docs/data-types/social-profile

+ Add microdata in platformIconBar

---

components/PlatformIconBar.vue
constant/index.js
nuxt.config.js

Seems csp does not complain about the json ld part

= Use JSON-LD for organization data

---

locales/client/cn.json
locales/client/en.json
locales/client/zh.json
pages/in/earn.vue
pages/in/settings/index.vue

* Enable binding wallet in settings page

---

nuxt.config.js
pages/_id/index.vue

+ Add Person json-ld in `:id` pages

! Fix missing name in site json-ld

---

.circleci/config.yml
locales/client/en.json
locales/client/zh.json
package.json
pages/in/civic/register.vue
store/modules/actions/user.js
test/e2e/specs/user.js
util/api/api.js

Depends on likecoin/likecoin-api-public#15

+ Support Civic Liker waiting list

---

constant/index.js

Reverts likecoin/likecoin-store#994
medium just re-enabled our app

Revert "- Hide medium from settings due to remote api not working"

---

server/index.js

🚑 Do not set csrf token via cookie in `/_nuxt` endpoints

---

components/dialogs/AuthDialogContent/SignInPortal.vue
experiments/index.js
experiments/registerCallout/index.js
locales/client/en.json
locales/client/zh.json
nuxt.config.js

Reverts likecoin/likecoin-store#1017
https://github.com/nuxt-community/google-optimize/blob/master/lib/plugin.js#L112
this line overwrite every other pending cookie

Revert "⚗ Add registerCallout experiment"

---

pages/in/settings/button.vue

Depends on likecoin/likecoin-button#127

🐛 Fix LikeButton preview

---

components/dialogs/AuthDialog.vue
util/FirebaseApp.js

🚸🔊 Add more error log in authDialog

🎨 Clean up code of redirect login flow

---

components/dialogs/OAuthPermissionDialog.vue
pages/in/oauth/index.vue

💄 Remove LikeCoin identity in OAuth permission page

---

components/dialogs/AuthDialog.vue
pages/in/settings/index.vue
pages/in/social/oauth/_platform/_id/index.vue

somehow fb sdk fails across all safari, but firebase works

🔥 Unify facebook login using firebase

---

components/dialogs/AuthDialog.vue

requirement: only log if dialog is is register state
also log events where register happen in signin state and when user switch signin state to register state

🔊 Add dialog signin status sensitive log

---

assets/dialog.scss
components/toolbars/ToolBars.vue

⏪ Revert change on z-index of md-dialog

---

components/dialogs/AuthDialog.vue
components/dialogs/AuthDialogContent/SignInPortal.vue
components/dialogs/BaseDialogV2.vue
nuxt.config.js
package-lock.json
package.json
plugins/gsap.client.js

Post-revamp of AuthDialog

---

components/home/SampleLikeButton.vue
pages/index.vue

Fix LikeButton introduction

---

assets/_button.scss
assets/index.scss
components/dialogs/AuthDialogContent/Register.vue
components/dialogs/AuthDialogContent/SignInPortal.vue
experiments/registerCallout/index.js
locales/client/zh.json

Depends on likecoin/liker-land#152 and likecoin/likecoin-button#203

Start experiment on sign-in portal

---

components/dialogs/AuthDialogContent/Register.vue
locales/client/cn.json
locales/client/en.json
locales/client/zh.json
test/e2e/specs/user.js

🚸 Change register checkbox default options

---

components/EthMixin.vue
components/SlidingMenu/AccountOverview.vue
components/UserInfoForm.vue
components/dialogs/AuthDialog.vue
layouts/in.vue
pages/_id/index.vue
pages/in/bonus/index.vue
pages/in/creator.vue
pages/in/index.vue
pages/in/settings.vue
pages/in/settings/button.vue
pages/in/tx/history.vue
pages/pay/_merchantId/index.vue
store/modules/actions/payment.js
store/modules/actions/user.js
store/modules/getters/user.js
util/CosmosHelper.js

Also other bug fix and minor refactor

✨ Add cosmos in payment page

---

locales/client/en.json
pages/in/unlock.vue

💬 Change pending like text

---

components/dialogs/OAuthPermissionDialog.vue

💄 Fine tune OAuth permission dialog

---

locales/client/zh.json

CTA changes

---

components/dialogs/AuthDialog.vue
store/modules/actions/authCore.js

🚑 Mitigate email not fetched in some oauth register

---

components/dialogs/AuthDialog.vue
store/modules/actions/authCore.js

Reverts likecoin/likecoin-store#1346

Revert "🚑 Mitigate email not fetched in some oauth register"

---

components/dialogs/AuthDialog.vue

💄 Make MetaMask sign in button more subtle

---

locales/client/cn.json
locales/client/en.json
locales/client/zh.json
pages/in/getapp.vue

🚸 Add about LikeCoin link in get app page

---

components/AuthCore/Register.vue
components/AuthCore/config.js
components/dialogs/AuthDialog.vue
experiments/registerCallout/index.js
nuxt.config.js

Switching between register and login, and prepare to use register initial screen for signup user flow

👽 Update according to latest authcore release 

---

middleware/authenticated.js
store/modules/actions/ui.js
store/modules/actions/user.js

Fixed client side login loses route state after login redirect complete

✨ Store post auth route to localstorage to support redirect auth flow

---

layouts/webflow.vue
pages/index.vue

Old version might cause `Webflow is undefined` on nav to `index`
Made webflow js to be a callback of jquery onload to prevent race of `window.jQuery` and `window.Webflow`

🐛 Fix Webflow loading race condition in SPA to index page

---

locales/client/en.json
pages/index.vue

Updates wordings with #DePub narrative

💬 Update copywriting

---

locales/client/zh.json

I fix the term in zh. 
There are many emoji in commit message (so cute). I'm not sure about the rule that commit type corresponds emoji, so i choose i think that are maybe correct.
If this PR be accepted, maybe add `hacktoberfest-accepted` label for me? Thank you <3

🌐 Fix term in zh version

---

pages/in/widget/pay/index.vue
util/CosmosHelper.js

🐛 Fix cosmos gas calculation did not include gas price

🔧 Add gas price in like pay

---

pages/in/widget/pay/index.vue

💬 Add default remarks for likepay

---

constant/index.js
pages/in/widget/pay/index.vue

To avoid confusion of another payment page in the like pay payment page

🚸 Popup portfolio page when clicking user id of likepay

---

components/LiquidQuickExchangeWidget/LiquidQuickExchangeWidget.vue

The SDK now can dynamically resize to accommodate the new KYC process

Allow auto-resizing of Liquid Quick Exchange Widget

---

components/dialogs/AuthDialog.vue

In preparation of passing `utm_source` from liker.land

🔊 Add utmSource in register payload

---

layouts/iscn.vue
locales/client/en.json
pages/in/tx/iscn/dev/_id/index.vue

💄 Update ISCN tx page UI

---

components/dialogs/AuthDialogContent/Register.vue

Related: https://github.com/likecoin/likecoin-api-public/pull/243

🔥 Remove email requirement from cosmosWallet registration

---

locales/client/en.json
pages/in/widget/iscn/index.vue

💄 Add URL display in ISCN widget

---

locales/client/en.json
locales/client/zh.json
pages/in/settings/index.vue
store/modules/actions/authCore.js
util/cosmos/desmos.js

Need some basic UI improvement

✨ Add desmos proof signing in authcore setting

---

pages/in/widget/iscn/index.vue
pages/in/widget/pay/index.vue

Allow like pay and updating metadata via keplr

⏪️ Revert Temp disable likepay keplr

---

util/Keplr.js

https://docs.keplr.app/api/#interaction-options
Allow 0 fee override by setting flag

🚸 Improve keplr login fee ux

---

locales/client/cn.json
locales/client/en.json
locales/client/zh.json
pages/in/widget/iscn-ar/index.vue
pages/in/widget/iscn/index.vue

Fill i18n to prevent language confusion

🌐 Add i18n for iscnar widget

---

pages/in/widget/iscn-ar/index.vue

Since no keplr on mobile, default the button to use authcore/likerid

✨ Default to authcore for mobile client in iscn-ar

---

plugins/vue-i18n.js
store/modules/ui.js

For now it seems saving language in local storage and restoring everytime is not a good idea

💩 Use sessionStorage instead of localStorage for locale

---

components/dialogs/AuthDialog.vue
components/dialogs/AuthDialogContent/Register.vue
pages/in/widget/iscn-ar/index.vue
pages/in/widget/iscn/index.vue
pages/in/widget/pay/index.vue
store/modules/actions/user.js
util/User.js

Allow user to use tx functions in like-co no matter new or old prefix

👽️ likeWallet support for widget and signin

---

components/SlidingMenu/AccountOverview.vue
components/UserInfoForm.vue
layouts/in.vue
pages/in/settings/index.vue
pages/in/tx/history.vue
store/modules/getters/user.js
util/User.js

This PR should be able to release before chain upgrade

✨ Support likeWallet sign-in

---

pages/in/tx/iscn/_id/index.vue

Fix creatorUser.entity.id to @id

:recycle: Fix creatorUser.entity.id to @id

---

components/toolbars/ToolBars.vue
locales/client/cn.json
locales/client/en.json
locales/client/zh.json
pages/in/tx/iscn/_id/index.vue

💄 Update blocking message for chain upgrade

---

package-lock.json
package.json
util/cosmos/iscn/sign.js

Check iscn-ar id only like prefix

:recycle: Check iscn-ar id only like prefix

---

components/Mission/ItemPlaceholder.vue
components/dialogs/AuthDialog.vue
locales/client/cn.json
locales/client/en.json
locales/client/zh.json
package-lock.json
package.json
util/client.js

Add toggle button for legacy frontend

---

pages/in/widget/iscn-ar/index.vue

passthrough qs `mint` to app-like-co which shows mint button in post iscn creation popup

✨ Passthrough qs `mint` in iscn-ar for nft minting test

---

nuxt.config.js

For some reason brave is caching our html pages. hope this meta tag would help

👽️ Add no cache header in html pages

---

util/EthHelper.js

For some reason web3 method doesn't like what metamask rpc returns now, so I just replace some with direct calls to window.ethereum as suggested in metamask guide

🐛 Fix legacy metamask login

---

.circleci/config.yml
nuxt.config.js
package-lock.json
package.json
plugins/AuthCore.client.js
store/modules/actions/authCore.js
util/CosmosHelper.js
util/cosmos/iscn/legacyDevQuery.js
util/cosmos/iscn/query.js
util/cosmos/iscn/sign.js

⚡️ Lazy load cosmjs to improve loading

---

constant/index.js
locales/client/zh.json

requires https://github.com/likecoin/likecoin-api-public/pull/378

🔧 Lower LikerId regex to min 5 char

---

pages/in/widget/iscn-ar/index.vue
pages/in/widget/iscn/index.vue
pages/in/widget/pay/index.vue

💄 Add logout button for logged in user in widgets

---

components/v2/dialogs/AuthDialogV2.vue

⚡️ Lazy load qrcode component

---

pages/in/widget/iscn-ar/index.vue

Support defining app.like.co nft portal qs in iscn-ar

✨ Pass iscn-ar qs to app.like.co

---

pages/in/widget/iscn-ar/index.vue

Allow iscn-ar to skip to nft portal with clicking continue by setting `mint=1`

✨ Add mint shortcut to nft portal

---

components/toolbars/ToolBars.vue
locales/client/cn.json
locales/client/en.json
locales/client/zh.json

🩹 Fix chain upgrade alert message

---

layouts/register.vue

🚸 Add logo link and help icon in register screen

---

locales/client/en.json
locales/client/zh.json
pages/in/settings/others.vue

[TAS-1543] ✨ Add export seed word widget link in other settings

---

pages/in/register/index.vue

User report redirection broken after oauth, revert this line until we know what is happening

⏪️ Revert change to oauth pathname check

---

components/v2/ProfileView.vue
locales/client/cn.json
locales/client/en.json
locales/client/zh.json

[TAS-2423] ♻️ Integrate image upload functionality into avatar component

---

locales/client/en.json
locales/client/zh.json

🚸 Add validation rules for Liker ID
